order_status= "complete order"
print(order_status[0])
print(order_status[12])
print(len(order_status))
print(order_status[0:8])
print(order_status[9:len(order_status)])
print(order_status[9:])
print(order_status[:])
print(order_status[-5:len(order_status)])
index=order_status.find(" ")
print(index)
print(order_status[index+1:len(order_status) ])

print(order_status[0:index])
print(order_status[0:15:2])
#reverse a string
print(order_status[::-1])
print(order_status.find('z'))
print(order_status.find('e'))
print(order_status.index('m'))
print(order_status.endswith("order"))
print(order_status.capitalize())
print(order_status.strip())
print(order_status.replace("complete","Completed"))